items = [
    {'id': 1, 'name': 'Laptop', 'cost': 1500},
    {'id': 2, 'name': 'Fan', 'cost': 500},
    {'id': 3, 'name': 'Mixer', 'cost': 356},
    {'id': 4, 'name': 'TV set', 'cost': 1200},
    {'id': 5, 'name': 'Iron', 'cost': 230},
    {'id': 6, 'name': 'Blender', 'cost': 360},
    {'id': 7, 'name': 'Fridge', 'cost': 3600},
    {'id': 8, 'name': 'Washing-mashine', 'cost': 2000},
    {'id': 9, 'name': 'Cooker', 'cost': 1950},
    {'id': 10, 'name': 'Vakuum cleaner', 'cost': 1000},
    {'id': 11, 'name': 'Hairdryer', 'cost': 150},
    {'id': 12, 'name': 'Air conditioner', 'cost': 1400},
    {'id': 13, 'name': 'Coffee grinder', 'cost': 80},
    {'id': 14, 'name': 'Juicer', 'cost': 60},
    {'id': 15, 'name': 'Dishwasher', 'cost': 2200},
    {'id': 16, 'name': 'Microwave oven', 'cost': 600},
]