# Generated by Django 3.2.9 on 2021-11-26 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='todoitem',
            name='tags',
            field=models.ForeignKey(default='general', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='items', to='todo_app.tags'),
        ),
    ]
